name: Build & Release APK

on:
  push:
    tags:
      - 'v*.*.*' # Trigger the job only when you push versioned tags (e.g., v1.0.0)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Step 3: Install Flet
      - name: Install Flet and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      # Step 4: Build the APK
      - name: Build APK
        env:
          PATH: ${{ env.PATH }}:~/.local/bin
        run: poetry run flet build apk -v

      # Step 5: Upload the APK as an artifact
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v3
        with:
          name: logistics-app-release-apk
          path: dist/*.apk

      # Step 6: Create a GitHub release and attach APK
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          files: dist/*.apk